# Generated by Django 3.0.1 on 2020-03-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amperage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('axis', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=14, max_digits=20)),
            ],
        ),
    ]
